/**
 * Localization registry and dictionaries.
 *
 * `releasedLocales` are shown in the interface. `plannedLocales` are declared so
 * that Hausa, Yoruba and Igbo can be added by supplying one more dictionary
 * object without touching component code. `audio` marks locales that have a
 * recorded spoken track available; no locale ships audio in v1.
 */

export type LocaleCode = "en" | "pcm" | "ha" | "yo" | "ig";

export type LocaleDefinition = {
  code: LocaleCode;
  htmlLang: string;
  /** Name of the locale written in English. */
  label: string;
  /** Name of the locale written in the locale itself. */
  nativeLabel: string;
  status: "released" | "planned";
  audio: boolean;
};

export const localeRegistry: Record<LocaleCode, LocaleDefinition> = {
  en: { code: "en", htmlLang: "en-NG", label: "English", nativeLabel: "English", status: "released", audio: false },
  pcm: { code: "pcm", htmlLang: "pcm-NG", label: "Nigerian Pidgin", nativeLabel: "Naija Pidgin", status: "released", audio: false },
  ha: { code: "ha", htmlLang: "ha-NG", label: "Hausa", nativeLabel: "Hausa", status: "planned", audio: false },
  yo: { code: "yo", htmlLang: "yo-NG", label: "Yoruba", nativeLabel: "Yorùbá", status: "planned", audio: false },
  ig: { code: "ig", htmlLang: "ig-NG", label: "Igbo", nativeLabel: "Igbo", status: "planned", audio: false },
};

export const releasedLocales = ["en", "pcm"] as const;
export type Locale = (typeof releasedLocales)[number];

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && (releasedLocales as readonly string[]).includes(value);
}

/** The locale a viewer is switched to when they press the language toggle. */
export function nextLocale(current: Locale): Locale {
  const index = releasedLocales.indexOf(current);
  return releasedLocales[(index + 1) % releasedLocales.length];
}

const en = {
  nav: {
    brand: "Smart Farming",
    brandTagline: "for Rural Nigeria",
    home: "Home",
    predict: "Predict",
    irrigate: "Irrigate",
    research: "Research",
    skipToContent: "Skip to main content",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
    useDarkTheme: "Use dark theme",
    useLightTheme: "Use light theme",
    languageGroup: "Language",
    switchTo: "Switch to",
    plannedLanguages: "Hausa, Yoruba and Igbo are planned for a later release.",
  },
  hero: {
    kicker: "M.Eng research, built for practical use",
    title: "Better crop decisions start with measured conditions.",
    body: "Enter seven soil and weather readings to explore a research-backed crop recommendation for your field.",
    ctaPredict: "Get a crop recommendation",
    ctaResearch: "Read the research",
    imageAlt: "A farmer and an agricultural extension officer taking field measurements on a Nigerian farm",
  },
  weather: {
    kicker: "Live field reference",
    title: "Uyo weather, observed now",
    body: "A live reference from OpenWeather. These readings do not change your prediction form.",
    imageAlt: "A weather station standing in a wet cassava field near Uyo",
    cardTitle: "Uyo, Akwa Ibom",
    live: "Live observation",
    stale: "Stale observation",
    refresh: "Refresh Uyo weather",
    loading: "Loading current Uyo conditions…",
    unavailable: "Live weather is temporarily unavailable.",
    retry: "Retry weather",
    lastKnown: "Showing the last observation saved on this device.",
    observedAt: "Observed",
    source: "Source: OpenWeather",
    notConfigured: "Live weather is not configured on this server yet.",
    temperature: "Temperature",
    feelsLike: "Feels like",
    humidity: "Humidity",
    cloudCover: "cloud cover",
    pressure: "Pressure",
    pressureDetail: "Atmospheric pressure",
    wind: "Wind",
    windDetail: "Surface wind speed",
    rain: "Rain, previous hour",
  },
  workflow: {
    kicker: "The prediction workflow",
    title: "Seven readings. One clear starting point.",
    body: "The model compares soil nutrients, climate and rainfall patterns across 22 crop classes.",
    imageAlt: "A field technician measuring soil beside agricultural testing tools",
    inputsLabel: "Seven crop model inputs",
    nutrients: "N, P, K",
    nutrientsDetail: "Soil nutrients",
    ph: "Soil pH",
    phDetail: "Acidity or alkalinity",
    climate: "Weather and rain",
    climateDetail: "Temperature, humidity, rainfall",
    cta: "Open the seven-input form",
  },
  evidence: {
    kicker: "Evidence before claims",
    title: "Strong benchmark results, stated with limits.",
    body: "The reported scores come from curated datasets. They are a software validation milestone, not a field guarantee.",
    imageAlt: "A Nigerian agricultural researcher reviewing data beside soil samples",
    metricsLabel: "Research summary metrics",
    configurations: "evaluated configurations",
    accuracy: "CatBoost held-out accuracy",
    classes: "crop classes",
    features: "input features",
    leaderboardTitle: "Top benchmark results",
    leaderboardNote: "Held-out accuracy",
    featureTitle: "Leading agronomic signals",
    featureNote: "Reported SHAP rank",
    rank: "Rank",
    viewFullTable: "View the full leaderboard",
  },
  context: {
    kicker: "Local context",
    title: "Nigerian evidence gives the model context.",
    body: "Soil maps, crop statistics and remote-sensing records were used to test whether the research remained agronomically relevant.",
    imageAlt: "Aerial view of smallholder farms and wetlands in southern Nigeria",
  },
  limits: {
    kicker: "Responsible use",
    title: "Decision support, not agronomic approval.",
    body: "Use the recommendation as a starting point and consult an extension officer before committing land, seed or irrigation resources.",
    imageAlt: "A farmer and an extension officer discussing a soil sample together",
    pointResearch: "Research-backed starting point",
    pointNoControl: "No automatic irrigation control",
  },
  predict: {
    kicker: "Crop recommendation",
    title: "Describe the conditions on your plot",
    body: "Use recent measurements where possible. Live Uyo weather is shown separately and is never inserted automatically.",
    note: "Use one consistent source for each reading. Current Uyo weather is informational and is never copied into this form.",
    submit: "Run crop recommendation",
    submitting: "Checking conditions",
    reset: "Clear form",
    exampleLabel: "Example",
    rangeLabel: "Research range",
    required: "Enter a value.",
    checkFields: "Check the highlighted measurements and try again.",
    envelopeHeading: "Outside the training envelope",
    envelopeBody: "These values are accepted, but the research dataset contains no comparable examples. Treat the result with extra caution.",
    fieldsLabel: "Seven soil and weather measurements",
    nitrogen: "Nitrogen",
    nitrogenHint: "Soil nitrogen from a laboratory or test-kit reading.",
    phosphorus: "Phosphorus",
    phosphorusHint: "Soil phosphorus from a laboratory or test-kit reading.",
    potassium: "Potassium",
    potassiumHint: "Soil potassium from a laboratory or test-kit reading.",
    temperature: "Temperature",
    temperatureHint: "Average air temperature over the growing period.",
    humidity: "Relative humidity",
    humidityHint: "Average relative humidity over the growing period.",
    soilPh: "Soil pH",
    soilPhHint: "Soil acidity. 7 is neutral, below 7 is acidic.",
    rainfall: "Rainfall",
    rainfallHint: "Total rainfall expected over the growing period.",
  },
  result: {
    heading: "Crop recommendation result",
    emptyIndex: "01",
    emptyTitle: "Your result will appear here.",
    emptyBody: "Complete all seven measurements to compare your conditions with the research dataset.",
    label: "Recommended crop",
    scorePrefix: "Top model score",
    alternatives: "Other model matches",
    important: "Important",
    explanations: "What moved this result",
    supports: "supports",
    opposes: "opposes",
    modelLabel: "Model",
    requestLabel: "Request",
  },
  errors: {
    invalidInput: "Some measurements were rejected by the prediction service. Check the highlighted fields.",
    offline: "You appear to be offline. Predictions need a network connection.",
    timeout: "The prediction service took too long to answer. Try again.",
    unavailable: "The prediction service is unavailable right now. Your measurements were not stored.",
    malformed: "The prediction service returned an unreadable response.",
    generic: "Prediction is temporarily unavailable.",
    tryAgain: "Try again",
  },
  research: {
    kicker: "David Edet Mbre, M.Eng",
    title: "A rigorous benchmark with a practical purpose.",
    body: "David Edet Mbre's M.Eng study compares eighteen configurations and proposes a low-resource path from sensor readings to farmer-facing guidance.",
    scopeKicker: "What was evaluated",
    scopeTitle: "One controlled comparison across model families.",
    scopeBody: "Seventeen architectures were trained on identical partitions. A tuned XGBoost variant produced the eighteenth evaluated configuration.",
    leaderboardKicker: "Model leaderboard",
    leaderboardTitle: "Every evaluated configuration, in one table.",
    leaderboardBody: "Rebuilt as a web-native table from the dissertation's canonical results so the numbers stay readable, searchable and screen-reader accessible.",
    leaderboardCaption: "Held-out accuracy and macro F1 for all eighteen evaluated configurations.",
    columnModel: "Configuration",
    columnFamily: "Family",
    columnAccuracy: "Accuracy",
    columnMacroF1: "Macro F1",
    featureKicker: "Explainability",
    featureTitle: "Rainfall, humidity and potassium carried the signal.",
    featureBody: "The reported SHAP analysis ranks the seven inputs by their contribution to the trained classifier.",
    methodKicker: "Methodological discipline",
    methodTitle: "High scores need stronger questions.",
    methodBody: "The dissertation treats benchmark performance as an upper bound and uses statistical checks to avoid choosing a model from one headline number.",
    provenanceKicker: "Data provenance",
    provenanceTitle: "Nigerian context was validation, not hidden training data.",
    provenanceBody: "The crop predictor was trained on the curated Crop Recommendation Dataset. Nigerian datasets helped assess soil, crop and remote-sensing relevance.",
    figureExpand: "Expand this figure",
    figureClose: "Close figure",
    figureSource: "Source",
    figureMethod: "Method",
    irrigationKicker: "Irrigation decision model",
    irrigationTitle: "A binary irrigate-now classifier, served with its limits stated.",
    irrigationBody: "The irrigation model is live. It answers one sensor-reading question for five crops, and each condition the release was gated on is resolved and disclosed below.",
    irrigationGate: "How each release condition was resolved",
    irrigationScope: "Crops the model knows",
    irrigationNoOverlap: "None of these five is among the 22 crops the recommender suggests, so 'recommend, then ask the model when to water' cannot chain. Watering advice for recommended crops comes from the guidance module instead.",
    guidanceKicker: "Watering guidance",
    guidanceTitle: "Schedules are authored rules, not a third model.",
    guidanceBody: "How often, how much, what time of day and what to do after rain come from FAO irrigation manuals and crop-specific sources, computed with a small open rule set for every crop the site can name. Each line shows the rule and inputs behind it, and every crop lists its sources.",
    statusKicker: "Live service status",
    statusTitle: "What this deployment is currently serving.",
    statusBody: "Read directly from the running service so the page cannot claim a production model that is not connected.",
    limitsTitle: "What this website does not claim",
    limitsBody: "No active Nigerian farm was used for external validation. The app does not guarantee yield, approve a planting decision, schedule or control irrigation equipment, or replace an agronomist. Watering guidance is authored advice, not a model output, and the irrigation model answers only for the five crops it was trained on.",
  },
  status: {
    label: "Model status",
    fixture: "Interface fixture",
    production: "Production model",
    notServing: "Not serving",
    taskCrop: "Crop recommendation",
    taskIrrigation: "Irrigation decision",
    servingMode: "Serving mode",
    loading: "Checking service status…",
    unavailable: "Service status is unavailable.",
    version: "Version",
    classes: "Classes",
    scoreKind: "Score kind",
    calibrated: "Calibrated confidence",
    uncalibrated: "Uncalibrated model score",
    accuracy: "Held-out accuracy",
    releaseGate: "Release gate",
    labelMapping: "Label disclosure",
    notMeasured: "Not measured in this deployment",
  },
  irrigate: {
    kicker: "Irrigation decision",
    title: "Should this field be watered right now?",
    body: "The irrigation model answers one question for one moment: given the soil moisture, temperature and humidity you measure now, water or not. It knows five crops.",
    note: "This model was trained on five crops, seven soil types and eight growth stages. Choose from those lists; anything else is rejected rather than guessed. None of the five is a crop the recommender suggests, so the two tools are separate.",
    fieldsLabel: "Field conditions",
    crop: "Crop",
    cropHint: "One of the five crops the model was trained on.",
    soilType: "Soil type",
    soilTypeHint: "As classified in the training data.",
    growthStage: "Growth stage",
    growthStageHint: "Where the crop is in its season.",
    moisture: "Soil moisture index",
    moistureHint: "From a soil moisture sensor or probe. 1 is bone dry, 100 is saturated.",
    temperature: "Air temperature",
    temperatureHint: "Current air temperature at the field.",
    humidity: "Relative humidity",
    humidityHint: "Current relative humidity at the field.",
    choose: "Choose…",
    submit: "Check irrigation",
    submitting: "Checking",
    reset: "Clear form",
    resultHeading: "Irrigation decision result",
    emptyTitle: "Your decision will appear here.",
    emptyBody: "Choose the crop, soil and stage, then enter three readings.",
    decisionIrrigate: "Irrigate now",
    decisionNo: "Do not irrigate now",
    scorePrefix: "Model probability of irrigating",
    responsibleUse: "A sensor-reading decision for this moment only. It does not schedule water, control a pump, or replace an extension officer.",
    modelUnavailable: "The irrigation model is not available on this deployment.",
  },
  guidance: {
    kicker: "Watering guidance",
    title: "Watering guidance for",
    intro: "Adjust the stage, soil and season to match your field.",
    stage: "Growth stage",
    soil: "Soil texture",
    season: "Season",
    stages: {
      establishment: "Establishment",
      vegetative: "Vegetative growth",
      flowering: "Flowering",
      yield_formation: "Fruit, grain or tuber formation",
      ripening: "Ripening",
    },
    soils: { sandy: "Sandy", loam: "Loam", clay: "Clay" },
    seasons: { dry: "Dry season", wet: "Wet season" },
    frequencyLabel: "How often",
    daily: "Every day",
    everyNDays: "Every {days} days",
    keepFlooded: "Keep {min}-{max} cm of standing water; top up about every {days} days",
    withhold: "Withhold water until {stage}",
    amountLabel: "How much each time",
    amount: "About {litres} litres per square metre (a {mm} mm depth)",
    timeLabel: "Best time of day",
    earlyMorning: "Early morning, before the heat. Leaves dry quickly, which limits fungal disease.",
    morningOrEvening: "Early morning or evening, when evaporation is lowest.",
    afterRainLabel: "After rain",
    criticalLabel: "Critical stage",
    criticalNow: "This crop is in a stage where water shortage costs yield directly. Do not miss a watering.",
    watchLabel: "Watch for",
    practiceLabel: "Practice",
    wetSeason: "In the wet season, water only if this many days pass without rain.",
    whyTitle: "Why this advice",
    basis: {
      eto_humid_table: "Reference evapotranspiration (ETo) for a humid climate at {temperatureC} °C: {etoMmPerDay} mm/day (FAO Training Manual 3, Table 5).",
      eto_heat_adjustment: "Above 32 °C, ETo raised by {adjustmentMm} mm/day.",
      eto_humidity_adjustment: "Relative humidity of {humidityPct}% adjusts ETo by {adjustmentMm} mm/day.",
      kc_stage: "Crop coefficient (Kc) at the {stage} stage is {kc}. Source: {source}",
      net_depth_fao4: "Net irrigation depth for {rooting}-rooted crops on {soil} soil is {netDepthMm} mm (FAO Training Manual 4).",
      interval_formula: "Interval = net depth ÷ daily crop use = {netDepthMm} ÷ {etcMmPerDay} ≈ {rawDays} → every {days} days.",
      flooded_rice: "Paddy loses {lossPerDayMm} mm/day to crop use plus {percolationMm} mm/day percolation on this soil, so 5 cm lasts about {topUpEveryDays} days.",
      withhold_low_need: "A drought-hardy crop outside its critical stage in the {season} season is not irrigated.",
      dry_rest_before_flowering: "{crop} sets flower buds only after a dry rest; watering during vegetative growth delays flowering.",
      rain_credit: "{rainMm} mm of rain replaces {rainMm} mm of irrigation; at {etcMmPerDay} mm/day that is about {skipDays} day(s).",
      waterlogging_risk: "{rainMm} mm exceeds the {netDepthMm} mm this soil holds in the root zone.",
      wet_season: "Wet-season rain usually covers this crop; irrigate only after the stated number of dry days.",
    },
    sourcesLabel: "Sources",
    unknownCrop: "Watering guidance for this crop is being prepared.",
    irrigationScope: "The irrigation model can answer 'water now?' for this crop.",
    noIrrigationScope: "The irrigation model does not know this crop; the guidance below is the only watering advice available for it.",
  },
  footer: {
    title: "Smart Farming for Rural Nigeria",
    copy: "An M.Eng machine-learning research project by David Edet Mbre.",
    linkPredict: "Crop recommendation",
    linkIrrigate: "Irrigation decision",
    linkResearch: "Research methods",
    linkWeather: "Weather source",
    note: "Two Architectures trained on seven open datasets: a 22-crop recommender and an irrigation decision aid, with watering schedules drawn from FAO irrigation manuals. Built for smallholder rain-fed farming in Nigeria's Guinea Savannah and Rainforest zones.",
  },
  errorPage: {
    kicker: "Application error",
    title: "This page could not load.",
    body: "Your farm measurements have not been stored. Try loading the page again.",
    notFoundKicker: "404",
    notFoundTitle: "This field is outside the map.",
    notFoundBody: "The page you requested is not part of this research application.",
    home: "Return home",
  },
};

/** Every released locale must supply this exact key set. */
export type Dictionary = typeof en;

const pcm: Dictionary = {
  nav: {
    brand: "Smart Farming",
    brandTagline: "for Rural Nigeria",
    home: "Home",
    predict: "Check crop",
    irrigate: "Water",
    research: "Research",
    skipToContent: "Jump go the main part",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    useDarkTheme: "Use dark theme",
    useLightTheme: "Use light theme",
    languageGroup: "Language",
    switchTo: "Change to",
    plannedLanguages: "Hausa, Yoruba and Igbo go come for later release.",
  },
  hero: {
    kicker: "M.Eng research wey fit help for farm",
    title: "Better crop choice dey start with correct measurement.",
    body: "Put seven soil and weather readings make the research model show crop wey fit your land.",
    ctaPredict: "Check crop recommendation",
    ctaResearch: "See the research",
    imageAlt: "Farmer and extension officer dey take measurement for one Nigerian farm",
  },
  weather: {
    kicker: "Live info from field",
    title: "Uyo weather as e be now",
    body: "Na live information from OpenWeather. E no go change anything for your prediction form.",
    imageAlt: "Weather station wey stand for wet cassava farm near Uyo",
    cardTitle: "Uyo, Akwa Ibom",
    live: "Live reading",
    stale: "Old reading",
    refresh: "Load Uyo weather again",
    loading: "We dey load Uyo weather…",
    unavailable: "Live weather no dey available now.",
    retry: "Try weather again",
    lastKnown: "Na the last reading wey save for this phone we dey show.",
    observedAt: "Dem check am",
    source: "Where e come from: OpenWeather",
    notConfigured: "Live weather never set for this server.",
    temperature: "Temperature",
    feelsLike: "E dey feel like",
    humidity: "Water for air",
    cloudCover: "cloud",
    pressure: "Pressure",
    pressureDetail: "Air pressure",
    wind: "Wind",
    windDetail: "How fast wind dey blow",
    rain: "Rain for last one hour",
  },
  workflow: {
    kicker: "How the prediction dey work",
    title: "Seven readings. One clear place to start.",
    body: "The model dey compare soil food, weather and rainfall for 22 different crops.",
    imageAlt: "Field worker dey measure soil near farm testing tools",
    inputsLabel: "The seven things wey model dey use",
    nutrients: "N, P, K",
    nutrientsDetail: "Food wey dey inside soil",
    ph: "Soil pH",
    phDetail: "Whether soil sour or no sour",
    climate: "Weather and rain",
    climateDetail: "Temperature, water for air, rainfall",
    cta: "Open the seven-input form",
  },
  evidence: {
    kicker: "Evidence before talk",
    title: "The test result strong, but e get limit.",
    body: "The scores come from clean research data. E no mean say field result go always reach the same level.",
    imageAlt: "Nigerian researcher dey look data near soil sample",
    metricsLabel: "Summary of the research numbers",
    configurations: "model setups wey dem test",
    accuracy: "CatBoost accuracy for test data",
    classes: "different crops",
    features: "things wey model dey use",
    leaderboardTitle: "Best test results",
    leaderboardNote: "Accuracy for test data",
    featureTitle: "Signals wey matter pass",
    featureNote: "SHAP rank wey dem report",
    rank: "Number",
    viewFullTable: "See the full table",
  },
  context: {
    kicker: "Local context",
    title: "Nigerian data help check the local context.",
    body: "Soil map, crop record and satellite data help check whether the research make sense for Nigerian farming.",
    imageAlt: "Sky view of small farms and wetland for south Nigeria",
  },
  limits: {
    kicker: "Use am well",
    title: "Na decision support, no be final agronomist approval.",
    body: "Use the result as where to start. Talk to extension officer before you spend money on land, seed or water.",
    imageAlt: "Farmer and extension officer dey talk about soil sample",
    pointResearch: "Place to start wey research back am",
    pointNoControl: "E no dey control irrigation by itself",
  },
  predict: {
    kicker: "Crop recommendation",
    title: "Tell us the condition for your farm",
    body: "Use recent measurement if you get am. Uyo live weather dey separate and e no go enter this form by itself.",
    note: "Use the same source for every reading. Uyo weather na information only, e no dey enter this form.",
    submit: "Check crop recommendation",
    submitting: "We dey check the condition",
    reset: "Clear everything",
    exampleLabel: "Example",
    rangeLabel: "Research range",
    required: "Put value.",
    checkFields: "Check the measurement wey we mark, then try again.",
    envelopeHeading: "E pass wetin research data cover",
    envelopeBody: "We go still run am, but research data no get example wey be like this. Take the result with care well well.",
    fieldsLabel: "Seven soil and weather measurement",
    nitrogen: "Nitrogen",
    nitrogenHint: "Nitrogen for soil, from lab or test kit.",
    phosphorus: "Phosphorus",
    phosphorusHint: "Phosphorus for soil, from lab or test kit.",
    potassium: "Potassium",
    potassiumHint: "Potassium for soil, from lab or test kit.",
    temperature: "Temperature",
    temperatureHint: "Average temperature for the planting season.",
    humidity: "Water wey dey air",
    humidityHint: "Average water for air during the planting season.",
    soilPh: "Soil pH",
    soilPhHint: "How sour the soil be. 7 na middle, below 7 na sour.",
    rainfall: "Rainfall",
    rainfallHint: "All the rain wey you expect for the planting season.",
  },
  result: {
    heading: "Crop recommendation result",
    emptyIndex: "01",
    emptyTitle: "Your result go show here.",
    emptyBody: "Fill the seven measurement make we compare your condition with the research data.",
    label: "Crop wey model recommend",
    scorePrefix: "Top model score",
    alternatives: "Other crops wey match",
    important: "Important",
    explanations: "Wetin move this result",
    supports: "dey support",
    opposes: "dey against",
    modelLabel: "Model",
    requestLabel: "Request",
  },
  errors: {
    invalidInput: "The prediction service no accept some measurement. Check the field wey we mark.",
    offline: "E be like say network no dey. Prediction need network.",
    timeout: "The prediction service slow too much. Try am again.",
    unavailable: "The prediction service no dey work now. We no keep your measurement.",
    malformed: "The prediction service send answer wey we no fit read.",
    generic: "Prediction no dey available now.",
    tryAgain: "Try again",
  },
  research: {
    kicker: "David Edet Mbre, M.Eng",
    title: "Serious research wey get practical purpose.",
    body: "David Edet Mbre M.Eng study compare eighteen model setups and show how sensor reading fit turn to useful farm guidance.",
    scopeKicker: "Wetin dem test",
    scopeTitle: "One controlled comparison across model family.",
    scopeBody: "Dem train seventeen architecture on the same data split. One tuned XGBoost make the eighteenth setup.",
    leaderboardKicker: "Model leaderboard",
    leaderboardTitle: "Every setup wey dem test, for one table.",
    leaderboardBody: "We build am again as web table from the dissertation numbers so the figures fit read well and screen reader fit read am.",
    leaderboardCaption: "Accuracy and macro F1 for all eighteen setup wey dem test.",
    columnModel: "Setup",
    columnFamily: "Family",
    columnAccuracy: "Accuracy",
    columnMacroF1: "Macro F1",
    featureKicker: "Explainability",
    featureTitle: "Rainfall, water for air and potassium carry the signal.",
    featureBody: "The SHAP analysis wey dem report rank the seven inputs by how dem help the model.",
    methodKicker: "Method discipline",
    methodTitle: "When score high, question suppose strong pass.",
    methodBody: "The dissertation treat benchmark score as the highest possible, and e use statistics check so say one headline number no go choose the model.",
    provenanceKicker: "Where data come from",
    provenanceTitle: "Nigerian data na validation, no be hidden training data.",
    provenanceBody: "Na the curated Crop Recommendation Dataset train the crop model. Nigerian data help check soil, crop and satellite relevance.",
    figureExpand: "Open this figure big",
    figureClose: "Close the figure",
    figureSource: "Where e come from",
    figureMethod: "Method",
    irrigationKicker: "Irrigation decision model",
    irrigationTitle: "Binary water-now classifier, wey we serve with im limit clear.",
    irrigationBody: "The irrigation model dey live. E dey answer one sensor-reading question for five crops, and every condition wey dem gate the release on don resolve and we show am below.",
    irrigationGate: "How we resolve each release condition",
    irrigationScope: "Crops wey the model sabi",
    irrigationNoOverlap: "None of these five dey among the 22 crops wey the recommender dey suggest, so 'recommend, then ask model when to water' no fit chain. Watering advice for recommended crop dey come from the guidance module instead.",
    guidanceKicker: "Watering guidance",
    guidanceTitle: "Schedule na rule wey person write, no be third model.",
    guidanceBody: "How often, how much, which time of day and wetin to do after rain come from FAO irrigation manual and crop sources, wey we calculate with small open rule for every crop wey the site fit name. Every line show the rule and input behind am, and every crop list where e come from.",
    statusKicker: "Live service status",
    statusTitle: "Wetin this deployment dey serve now.",
    statusBody: "We dey read am straight from the running service so this page no go claim production model wey no connect.",
    limitsTitle: "Wetin this website no dey claim",
    limitsBody: "Dem no use any active Nigerian farm for outside validation. This app no dey promise yield, e no dey approve planting decision, e no dey plan or control irrigation machine, and e no fit replace agronomist. Watering guidance na advice wey person write, no be model output, and the irrigation model dey answer only for the five crops wey dem train am with.",
  },
  status: {
    label: "Model status",
    fixture: "Interface fixture",
    production: "Production model",
    notServing: "E no dey serve",
    taskCrop: "Crop recommendation",
    taskIrrigation: "Irrigation decision",
    servingMode: "How e dey serve",
    loading: "We dey check service status…",
    unavailable: "Service status no dey available.",
    version: "Version",
    classes: "Classes",
    scoreKind: "Score type",
    calibrated: "Calibrated confidence",
    uncalibrated: "Model score wey no calibrate",
    accuracy: "Accuracy for test data",
    releaseGate: "Wetin must happen before release",
    labelMapping: "Label disclosure",
    notMeasured: "Dem no measure am for this deployment",
  },
  irrigate: {
    kicker: "Irrigation decision",
    title: "Make we water this field now?",
    body: "The irrigation model dey answer one question for one moment: with the soil moisture, temperature and humidity wey you measure now, water or no water. E sabi five crops.",
    note: "Dem train this model with five crops, seven soil type and eight growth stage. Choose from those list; anything else go bounce, e no go guess. None of the five na crop wey the recommender dey suggest, so the two tools dey separate.",
    fieldsLabel: "Field condition",
    crop: "Crop",
    cropHint: "One of the five crop wey dem train the model with.",
    soilType: "Soil type",
    soilTypeHint: "As dem classify am for training data.",
    growthStage: "Growth stage",
    growthStageHint: "Where the crop reach for the season.",
    moisture: "Soil moisture index",
    moistureHint: "From soil moisture sensor or probe. 1 na dry finish, 100 na full of water.",
    temperature: "Air temperature",
    temperatureHint: "Air temperature for the field now.",
    humidity: "Water wey dey air",
    humidityHint: "Relative humidity for the field now.",
    choose: "Choose…",
    submit: "Check irrigation",
    submitting: "We dey check",
    reset: "Clear everything",
    resultHeading: "Irrigation decision result",
    emptyTitle: "Your answer go show here.",
    emptyBody: "Choose crop, soil and stage, then put the three readings.",
    decisionIrrigate: "Water am now",
    decisionNo: "No water am now",
    scorePrefix: "Model probability say make you water",
    responsibleUse: "Na decision for this moment from sensor reading only. E no dey plan watering, e no dey control pump, and e no fit replace extension officer.",
    modelUnavailable: "The irrigation model no dey available for this deployment.",
  },
  guidance: {
    kicker: "Watering guidance",
    title: "Watering guidance for",
    intro: "Change the stage, soil and season make e match your field.",
    stage: "Growth stage",
    soil: "Soil texture",
    season: "Season",
    stages: {
      establishment: "When plant just start",
      vegetative: "Vegetative growth",
      flowering: "Flowering",
      yield_formation: "When fruit, grain or tuber dey form",
      ripening: "Ripening",
    },
    soils: { sandy: "Sandy", loam: "Loam", clay: "Clay" },
    seasons: { dry: "Dry season", wet: "Rainy season" },
    frequencyLabel: "How often",
    daily: "Every day",
    everyNDays: "Every {days} days",
    keepFlooded: "Keep {min}-{max} cm water for ground; add water about every {days} days",
    withhold: "Hold water until {stage}",
    amountLabel: "How much each time",
    amount: "About {litres} litre for every square metre ({mm} mm deep)",
    timeLabel: "Best time of day",
    earlyMorning: "Early morning, before sun hot. Leaf go dry quick, so fungus no go come.",
    morningOrEvening: "Early morning or evening, when sun no dey dry water.",
    afterRainLabel: "After rain",
    criticalLabel: "Critical stage",
    criticalNow: "This crop dey stage where water shortage go reduce harvest straight. No miss any watering.",
    watchLabel: "Watch for",
    practiceLabel: "Practice",
    wetSeason: "For rainy season, water only if this number of days pass without rain.",
    whyTitle: "Why we talk so",
    basis: {
      eto_humid_table: "Reference evapotranspiration (ETo) for humid weather at {temperatureC} °C: {etoMmPerDay} mm/day (FAO Training Manual 3, Table 5).",
      eto_heat_adjustment: "Above 32 °C, ETo go up by {adjustmentMm} mm/day.",
      eto_humidity_adjustment: "Relative humidity of {humidityPct}% change ETo by {adjustmentMm} mm/day.",
      kc_stage: "Crop coefficient (Kc) for {stage} stage na {kc}. Source: {source}",
      net_depth_fao4: "Net irrigation depth for crop with {rooting} root for {soil} soil na {netDepthMm} mm (FAO Training Manual 4).",
      interval_formula: "Interval = net depth ÷ daily crop use = {netDepthMm} ÷ {etcMmPerDay} ≈ {rawDays} → every {days} days.",
      flooded_rice: "Paddy dey lose {lossPerDayMm} mm/day to crop use plus {percolationMm} mm/day wey sink for this soil, so 5 cm go last about {topUpEveryDays} days.",
      withhold_low_need: "Crop wey fit bear dry weather, outside critical stage for {season} season, no need irrigation.",
      dry_rest_before_flowering: "{crop} dey form flower bud only after dry rest; if you water am during vegetative growth, flowering go delay.",
      rain_credit: "{rainMm} mm rain replace {rainMm} mm irrigation; at {etcMmPerDay} mm/day that na about {skipDays} day(s).",
      waterlogging_risk: "{rainMm} mm pass the {netDepthMm} mm wey this soil fit hold for root area.",
      wet_season: "Rainy season rain dey usually cover this crop; water only after the number of dry days wey we talk.",
    },
    sourcesLabel: "Where e come from",
    unknownCrop: "Watering guidance for this crop still dey come.",
    irrigationScope: "The irrigation model fit answer 'water now?' for this crop.",
    noIrrigationScope: "The irrigation model no sabi this crop; the guidance below na the only watering advice wey dey for am.",
  },
  footer: {
    title: "Smart Farming for Rural Nigeria",
    copy: "Na M.Eng machine-learning research project by David Edet Mbre.",
    linkPredict: "Crop recommendation",
    linkIrrigate: "Irrigation decision",
    linkResearch: "Research method",
    linkWeather: "Where weather come from",
    note: "Two Architectures wey dem train with seven open datasets: one dey recommend crop from 22 options, the other one dey tell you whether to water now. The watering plan come from FAO irrigation manual. Dem build am for small-scale rain-fed farming for Nigeria Guinea Savannah and Rainforest zones.",
  },
  errorPage: {
    kicker: "App error",
    title: "This page no fit load.",
    body: "We no keep your farm measurement. Try load the page again.",
    notFoundKicker: "404",
    notFoundTitle: "This field no dey the map.",
    notFoundBody: "The page wey you ask for no dey this research app.",
    home: "Go back home",
  },
};

export const copy: Record<Locale, Dictionary> = { en, pcm };
